---
title: '09.30'
author: "gary"
date: "2020/9/30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## fish
```{r}
library(vegan)
# Load additionnal functions
source("panelutils.R")
spe <- read.csv("data/DoubsSpe.csv", row.names=1)
env <- read.csv("data/DoubsEnv.csv", row.names=1)
spa <- read.csv("data/DoubsSpa.csv", row.names=1)

library(ade4)
data(doubs)

spe
spe[1:5,1:10]
head(spe)
nrow(spe)	
ncol(spe)		
dim(spe)
colnames(spe)		
rownames(spe)	
summary(spe)	

range(spe)
#Count cases for each abundance class
(ab <- table(unlist(spe)))

barplot(ab, las=1, xlab="Abundance class", ylab="Frequency", col=gray(5:0/5))
sum(spe==0)
sum(spe==0)/(nrow(spe)*ncol(spe))



plot(spa, asp=1, type="n", main="Site Locations", xlab="x coordinate (km)", ylab="y coordinate (km)")
lines(spa, col="light blue")
text(spa, row.names(spa), cex=0.8, col="red")
text(50, 10, "Upstream", cex=1.2, col="red")
text(30, 120, "Downstream", cex=1.2, col="red")

par(mfrow=c(1,4))
xl <- "x coordinate (km)"
yl <- "y coordinate (km)"
plot(spa, asp=1, col="brown", cex=spe$TRU, main="Brown trout", xlab=xl, ylab=yl) 
lines(spa, col="light blue", lwd=2)
plot(spa, asp=1, col="brown", cex=spe$OMB, main="Grayling", xlab=xl, ylab=yl)  
lines(spa, col="light blue", lwd=2)
plot(spa, asp=1, col="brown", cex=spe$BAR, main="Barbel", xlab=xl, ylab=yl)  
lines(spa, col="light blue", lwd=2)
plot(spa, asp=1, col="brown", cex=spe$BCO, main="Common bream", xlab=xl, ylab=yl) 
lines(spa, col="light blue", lwd=2)
```

## ggplot
```{r}
library(ggplot2)
ggplot(data=iris, aes(x=Sepal.Length, y=Sepal.Width, color=Species)) +
 geom_point(size=3)
ggplot(iris, aes(x=1:150, y=Sepal.Length, color=Species)) + geom_point()

iris.index.plot <- function(x){
  ggplot(iris, aes(x=1:nrow(iris), y=iris[,x], color=Species)) + 
    geom_point() +
    labs(x=names(iris)[x], y="values") 
}
index.list <- lapply(1:4, iris.index.plot)
library(grid)
library(gridExtra)
marrangeGrob(index.list, nrow=2, ncol=2, top="")
```


