---
title: "課堂練習模版"
author: "gary"
date: "2020-11-29"
output: html_document
params:
  id: "410678019"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
old_fct <- 
  factor(c("4以下","5-10","11-15"))
levels(old_fct) # 依序下的各類別名稱

levels(old_fct) <- c("青少年", "幼兒", "兒童")
levels(old_fct)
old_fct
```

```{r}
set.seed(2020)
gender <- sample(c("M","F"), 10000, replace = T)
head(gender)

gender.factor <- factor(gender)
levels(gender.factor)
levels(gender.factor) <- c("女","男")
head(gender.factor)
```

```{r}
old_fct2 <- 
  factor(c("4以下","5-10","11-15", "5-10"))
levels(old_fct2)
levels(old_fct2) <- c("4以下","5-10","11-15")
old_fct2
```

### 整併
```{r}
set.seed(2020)
ages_chr <- sample(c("4以下","5-9","10-14", "15-19"), 20, replace=T)
ages_chr

ages_fctBy5 <- 
  factor(
    ages_chr,
    levels = c("4以下","5-9","10-14", "15-19")
  )

levels(ages_fctBy5)
table(ages_fctBy5)

levels(ages_fctBy5) <- c("10以下", "10以下", "10以上", "10以上")
table(ages_fctBy5)
```

### 新增
```{r}
set.seed(2020)
ages_chr <- sample(c("4以下","5-9","10-14", "15-19"), 10, replace=T)
ages_chr

data_fct <- factor(ages_chr)
length(data_fct)

data_fct[[11]] <- c("10-14")
data_fct
data_fct[c(12, 13)] <- c("5-9","15-19")
data_fct
```

```{r}
levels(data_fct) 
data_fct[[14]] <- "20-24"
data_fct[[14]]
levels(data_fct)[[5]] <- "20-24"

levels(data_fct)
data_fct[[14]] <- "20-24"
data_fct
```

```{r}
ages_chr <- sample(c("5-9","10-14", "15-19"), 8, replace=T)
data_fct <- factor(ages_chr,
                   levels = c("5-9","10-14", "15-19"),
                   ordered = T)
# 新增類別
levels(data_fct)[c(4, 5)] <- c("20-24", "4以下")
# 新增資料
data_fct[c(9, 10, 11, 12)] <- c("20-24", "10-14", "15-19", "4以下")
# factor parsing修正排序
data_fct <- factor(
  data_fct,
  levels = c("4以下", "5-9","10-14", "15-19", "20-24")
)
data_fct
```

### ok
```{r}
# 非類別資料
numVect <- c(2, 5, 7)
# 新增c(6, 10)
numVect <- c(numVect, c(6,10))
numVect

# 類別資料
fctVector <- factor(c("a","b", "c", "a"))
# 新增 'a', 'c'
fctVector
fctVector <- c(fctVector, c('a','c'))
fctVector
```

```{r}
a <- c(Mary=178, Jack=165)
attr(a, "family") <- "Johnson"
attributes(a)

b <- c(Ben=170, David=172)
attr(b, "family") <- "Jenson"
attributes(b)

a_b <- c(a, b)
attributes(a_b)

list_ab <- list(a, b)
list_ab
attributes(list_ab)
attributes(a)
attributes(b)
```

### ok
```{r}
fct_a <- factor(c('a','d','e'))
fct_b <- factor(c("a","e","j"))

fct_ab <- 
  list(fct_a, fct_b)

unlist(fct_ab)
```

```{r}
library(stringr)
library(glue)
thatsAlright <- 
  jsonlite::fromJSON(
    "https://www.dropbox.com/s/f3ox7rd5favr0o0/thatsAlright.json?dl=1"
  )
View(thatsAlright)
```

### ok
```{r}
# 字串向量長度
length(c("I will"))
# 每個元素值有幾個字元(包含符號與空格)
str_length(c("I will"))

# 字串向量長度
length(thatsAlright)
# 每個元素值有幾個字元
str_length(thatsAlright)
```

```{r}
line67 <- thatsAlright[c(6,7)]
line67

str_split(line67, ",") -> line67_spilt
str(line67_spilt)
```

### ok
```{r}
pattern="you" 
# 'you'是否出現在第1,2,3,...最後一句
pick_you <- str_detect(thatsAlright, pattern="you")
str_view_all(thatsAlright[pick_you],"you")

# 哪幾句有'you'出現
whichHas_you <- str_which(thatsAlright, pattern="you")
whichHas_you
str_view_all(thatsAlright[whichHas_you],"you")
whichHas_you_fromPick <- which(pick_you)
whichHas_you_fromPick
```

```{r}
# 只留下有出現'you'字眼的句子
onlyYou <- str_subset(thatsAlright, pattern="you")

length(thatsAlright)
length(onlyYou)

# 每一句有幾個"you"
countEach_you <- str_count(thatsAlright,
                           pattern="you")
countEach_you
str_view_all(
  thatsAlright[1:10], pattern="you")
```

### ok
```{r}
patternWithBoundary="\\byou\\b"

str_view_all(
  c("I am yours",
    "And you?",
    "Young and smart", 
    "It means that you and I are lucky"),
  pattern=patternWithBoundary
)
```

### important
```{r}
Rmdfiles <- c("file1.Rmd", "file2.R", "file3.rmd", "file4.RMD", "myRmd.R")
SchoolIds <- c("410973029", "410988011", "410974023","410783025","710773022","410788021","410673124","410873051","49988001")

Rmdfiles
regexPattern="[Rr][Mm][Dd]"
str_subset(
  Rmdfiles, pattern=regexPattern)

SchoolIds
regexPattern="[4](108|109)(73|88)"
str_subset(
  SchoolIds, pattern=regexPattern)

str_subset(
  SchoolIds,
  pattern="[4](108|109)(73|88)")
str_subset(
  SchoolIds,
  pattern="4(108|109)(73|88)")
```

```{r}
str_subset(Rmdfiles, pattern = regex("rmd", ignore_case = T))
```


```{r}
sameIdentities <- c("臺北市", "台北市", "台北大學", "臺北大學", "基隆市")

str_detect(
  sameIdentities, pattern="[台臺]")
str_view_all(
  sameIdentities, pattern="[台臺]")

str_extract(
  sameIdentities, pattern="[台臺]北市")
```

### ok
```{r}
dragonPeople <-
  c(
    "住在台北市的臺北人也常被稱為天龍人")
str_extract(
  dragonPeople,
  pattern="[台臺]北[市人]"
)
# 當一個元素值內的文字規律可多次出現時用_all來一網打盡，否則只處理第一個出現的規律
str_extract_all(
  dragonPeople,
  pattern="[台臺]北[市人]"
)
```

### ok
```{r}
Rmdfiles # length=5
str_replace(
  Rmdfiles,
  pattern = rep("[Rr][Mm][Dd]",5),
  replacement = rep("Rmd",5)
)

Rmdfiles # length=5
str_replace(
  Rmdfiles,
  pattern = "[Rr][Mm][Dd]",
  replacement = "Rmd"
)
```

```{r}
emailContent <- '親愛的_name_朋友好，

  恭喜你，你的電子發票號碼_invoiceNumber_ 差點中獎。'
cat(emailContent)

replacementNamedVector <- c(
  "_name_" = "小新",
  "_invoiceNumber_" = "EF-89400133"
)

synthesizedContent <- str_replace_all(
  emailContent,
  replacementNamedVector
)
cat(synthesizedContent)
```























































