---
title: "課堂練習模版"
author: "gary"
date: "2020-11-24"
output: html_document
params:
  id: "410678019"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
AA = c(Mary=176, John=188, Jenny= 165, Kate=170)
LL = list(
  Mary=list(176,"Taipei"),
  John=list(188,"New Taipei"),
  Jenny=list(165,"Taichung"),
  Kate=list(170,"Hualien")
)
```

## extract 1 element
```{r}
AA[[1]]
AA[1]
LL[[1]]
LL[1]
LL$Mary 
```

```{r}
str(LL[[1]])
str(LL[1])
```

```{r}
AA[c(1,4)]
LL[c(1,4)]
AA[c("Mary","Kate")]
LL[c("Mary","Kate")]
AA[c(T, F, F, T)]
LL[c(T, F, F, T)]
```

```{r}
a <- c(2, 5, 7)
a[[4]]
a[[4]] <- 8
print(a)
```

```{r}
library(lubridate)
restaurant = "すき家 Sukiya (新北三峽店)"
date = lubridate::mdy("Nov 10, 2020")
order = list(
  list(
    item="蕃茄牛丼",
    quantity=1
  ) # 這裡少了一筆 "起司蕃茄牛丼"
)
total = 328
```

```{r}
oneOrder <- list(
  "restaurant"=restaurant,
  "date"=date,
  "order"=order,
  "total"=total
)
str(oneOrder)
```

```{r}
oneOrder$order[[2]]
oneOrder$order[[2]] <- list(
    item="起司蕃茄牛丼",
    quantity=1
  )
template <- oneOrder$order[[1]]

template$item <- "起司蕃茄牛丼"
template$quantity <- 1

oneOrder$order[[2]] <- template
```

```{r}
a <- c(2, 5, 7)
a[c(4,5)]
a[c(4,5)] <- c(8,12)
print(a)
```

```{r}
currentNumberOfOrder <- length(oneOrder$order)
# new order sequence number
newOrderSeq <- 1:2 + currentNumberOfOrder
oneOrder$order[newOrderSeq]
class(oneOrder$order)
```

```{r}
oneOrder$order[
  newOrderSeq
] <- list(
  item1_value,
  item2_value
)
```

```{r}
oneOrder$order[
  newOrderSeq
] <- 
  list(
    list(
      item="牛丼飯",
      quantity=1
    ),
    list(
      item="豬排飯",
      quantity=1
    )
  )

View(oneOrder)
```

```{r}
# 取出目前已有的子元素一個當模版
secondItem <- oneItem <- oneOrder$order[[1]]

oneItem$item <- "牛丼飯"
oneItem$quantity <- 1
secondItem$item <- "豬排飯"
secondItem$quantity <- 1

oneOrder$order[newOrders] <- list(
  oneItem, secondItem
)
```

```{r}
LL0 <- LL <- list(
  "Mary was born on", 
  ymd("1995-7-1"),
  "John was born on",
  ymd("1997-10-27")
  )
LL[[2]]
LL[[2]] <- ymd("1995-7-8")
print(LL)
```

```{r}
oneOrder$order[[1]]$quantity
oneOrder$order[[1]]$quantity <- 2
```

```{r}
LL <- LL0
LL[c(2,4)]
LL[c(2,4)] <- 
  list(
    ymd("1995-7-8"),
    ymd("1997-10-17")
  )
print(LL[c(2,4)])
```

```{r}
allMyOrders0 <- allMyOrders <-  # allMyOrder0等一下還原用
  list(
    oneOrder
  )
```

```{r}
anotherOrder <- 
  list(
    restaurant="古橋飲食店",
    date=lubridate::mdy("Nov 9, 2020"),
    order=list(
      list(
        item="古早味排骨飯",
        quantity=1
      )
    ),
    total=89
  )
thirdOrder <-
  list(
    restaurant="Tijo Kitchen",
    date=lubridate::mdy("Nov 8, 2020"),
    order=list(
      list(
        item="韓式泡菜黑咖哩飯",
        quantity=1
      )
    )
  )

allMyOrders[[2]] <- anotherOrder
allMyOrders[[3]] <- thirdOrder

str(allMyOrders)
```

```{r}
allMyOrders <- allMyOrders0
allMyOrders[c(2,3)] <- list(
  anotherOrder,
  thirdOrder
)
```

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
example$name[c(T, F, T, F)]
str(example[c("name","height")])

pick_above170 <- example$height >= 170
example$height
c(175, 166, 170, 160) >= 170

example$name[pick_above170]
```

```{r}
example$birthday
class(example$birthday)
typeof(example$birthday)
print(example[c("name","birthday")])

pick_after98 <- example$birthday >= lubridate::ymd("1998-01-01")
example$name[pick_after98]
```

```{r}
print(example[c("name","allowance")])

pick_allowanceOver1000 <- example$allowance >= "1001-2000"
example$name[pick_allowanceOver1000]
example$allowance <- 
  ordered(example$allowance)
```

### ok
```{r}
example$allowance %in% c("1001-2000", "2000+")
```

```{r}
example$allowance <-
  factor(
    example$allowance,
    levels=c("0-1000", "1001-2000", "2000+"),
    ordered = T # 設定為可排序factor
  )
pick_allowanceOver1000 <- example$allowance >= "1001-2000"
example$name[pick_allowanceOver1000]
```

```{r}
print(example[c("name","bloodType")])
pick_bloodB <- example$bloodType == "B"
example$name[pick_bloodB]
```

### ok
```{r}
sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)
pick_evens <- (sequenceNums %% 2) == 0
sequenceNums[pick_evens] 
```

```{r}
x <- c(1,5,8)
y <- c(5,8)

# x裡的元素值是不是屬於y集合
x %in% y
```

```{r}
print(example[c("name","residence")])

set_TaipeiMetro <- c("Taipei","New Taipei")
pick_fromTaipeiMetro <- example$residence %in% set_TaipeiMetro
example$name[pick_fromTaipeiMetro]
```

```{r}
with(example,
     {
       set_TaipeiMetro <- c("Taipei","New Taipei")
       pick_fromTaipeiMetro <- residence %in% set_TaipeiMetro # residence not defined
       name[pick_fromTaipeiMetro] # name not defined
     }) -> whoAreFromTaipeiMetro
whoAreFromTaipeiMetro
```

```{r}
pick_not_fromTaipeiMetro <- ! pick_fromTaipeiMetro
# 或
pick_not_fromTaipeiMetro <- !(example$residence %in% set_TaipeiMetro) # (..) 裡面會先運算完才做外面!的處理

print(example[c("name","residence")])
example$name[pick_fromTaipeiMetro]
example$name[pick_not_fromTaipeiMetro]
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")

x2
is.na(x2)

c(22,NA,18) -> a
# a==NA
is.na(a)
```

```{r}
print(example[c("name","weight")])

pick_na <- is.na(example$weight)
example$name[pick_na]
```

### ok
```{r}
print(example[c("name","hobby")])

pick_loveFood <- stringr::str_detect(example$hobby,"美食")
example$name[pick_loveFood]

example[["hobby2"]] <- c("美食", "時尚", "美食", "旅遊")

print(example[c("name", "hobby2")])
pick_loveFood2 <- example$hobby2 == "美食"
example$name[pick_loveFood2]
```

```{r}
str(example)
pick_above170 <- example$height >= 170
pick_bloodB <- example$bloodType == "B"
pick_loveFood <- 
  stringr::str_detect(example$hobby,"美食")
pick_na <- is.na(example$weight)
pick_after98 <- 
  example$birthday >= lubridate::ymd("1998-01-01")
set_TaipeiMetro <- c("Taipei","New Taipei")
pick_fromTaipeiMetro <- 
  example$residence %in% set_TaipeiMetro

str(example[c("name","hobby","bloodType")])
example$name[
    pick_loveFood & pick_bloodB
  ]

example[c("name","birthday","residence")]
example$name[
  pick_after98 | !pick_fromTaipeiMetro
]

example$name[
  pick_after98 & pick_fromTaipeiMetro & pick_bloodB
]
```

```{r}
set.seed(2020)
ages_chr <- sample(c("4以下","5-10","11-15"), 15, replace=T)
ages_chr

#ok
unique(ages_chr)
table(ages_chr)

factor(
  字面資訊向量
)
ages_fct1 <- 
  factor(
    ages_chr
  )

table(ages_fct1)
table(ages_chr)

factor(
  字面資訊向量,
  levels = 類別資訊呈現時的先後順序向量
)

ages_fct2 <- 
  factor(
    ages_chr,
    levels = c("4以下","5-10","11-15")
  )

table(ages_fct1)
table(ages_fct2)

ages_fct2[[3]] #4以下
ages_fct2[[6]] #5-10
ages_fct2[[3]] > ages_fct2[[6]]

factor(
  字面資訊向量,
  levels = 類別資訊呈現時的先後順序向量,
  ordered = TRUE # 告訴電腦類別呈現的先後順序，即可比大小的小（先）大（後）順序
)

ages_fct3 <- 
  factor(
    ages_chr,
    levels = c("4以下","5-10","11-15"),
    ordered = T
  )

ages_fct3[[3]] #4以下
ages_fct3[[6]] #5-10
ages_fct3[[3]] > ages_fct3[[6]]
ages_fct3[[6]] < "11-15" # 也可以用文字寫下levels中有的分類
ages_fct3[[6]] < ages_fct3[[3]]

# 忘了告訴電腦是ordered factor
ages_fct2_order = factor(ages_fct2, ordered=T)
ages_fct2_order
# 也可以
ages_fct2_order = as.ordered(ages_fct2)

# 忘了告訴電腦呈現順序是"11-15","5-10","4以下"
ages_fct3_newLevels = 
  factor(
    ages_fct3, 
    levels = c("11-15","5-10","4以下")
  )
ages_fct3_newLevels
is.ordered(ages_fct3_newLevels)
```










