---
title: "課堂練習模版"
author: "gary"
date: "2020-12-08"
output: html_document
params:
  id: "410678019"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

### important
```{r}
library(stringr)
set.seed(2020)
d1 <- sample(c(rep("4",10),rep("3",3),rep("7",3)), 25, replace=T)
d2 <- sample(98:109, 25, replace=T)
d3 <- sample(c("73", "74", "78", "83", "72"))
d4 <- sample(1:120, 25, replace=T)
d4 <- str_pad(d4, 3, side = "left", pad="0")
schoolIds <- paste0(d1,d2,d3,d4)
schoolIds

# {x} 前方卷帶連裝x條
str_subset(schoolIds,
           pattern='[0123456789]{9}')
str_subset(schoolIds,
           pattern='[0-9]{9}')
str_subset(schoolIds,
           pattern='[:digit:]{9}')
```

```{r}
myLove2R <- c("我實在是太愛太愛太愛愛R課程了",
  "我才是太愛太愛太太愛太太太愛R了",
  "我則是太愛愛太愛太愛愛愛R了",
  "找我太太聊天，我太太愛理不理的，我只好回去練我最愛的R。")

str_view_all(myLove2R, "(太愛){2}")

# {1,2} 前面卷帶裝1～2條 
str_view_all(myLove2R, "太[愛]{1,2}")
str_view_all(myLove2R, "太愛{1,2}") # 卷帶只有一個字，可不寫[]

# ? 前面卷帶不確定要不要裝（要裝也只會裝1條）
str_view_all(myLove2R, "太愛[愛]?")

# 沒有限制的愛(指1條或以上)
str_view_all(myLove2R, "太[愛]+")
str_view_all(myLove2R, "太[愛]{1,}")

# 不管愛不愛，不管愛多深
str_view_all(myLove2R, "太[愛]*")
```

### important
```{r}
str_view_all(myLove2R, "太愛[愛]?")
str_view_all(myLove2R, "太+愛+")
str_view_all(myLove2R, "太+愛+(?!理不理)")
```

### ok 中文
```{r}
addresses <- c(
  '臺中市后里區公館里尾社路385號',
  '新竹市東區科學園路125號1樓',
  '新竹市北區竹光路99號',
  '金門縣金城鎮賢庵里山前33號',
  '臺中市南屯區工業區二十四路23號1樓')

str_extract(
  addresses,
  "(?<=[縣市])[\u4E00-\u9FFF]+[區鎮]"
)

# 字元排除卷帶[^XYZ]：要排除的字元XYZ
# 區鎮前面不能再有區這個字
str_extract(
  addresses,
  "(?<=[縣市])[^區]+[區鎮]"
)
```

```{r}
Rmdfiles <- c("file1.Rmd", "file2.R", "file3.rmd", "file4.RMD", "myRmd.R")

str_subset(
  Rmdfiles, "[Rr][Mm][Dd]"
)

# 在開頭：^目標
# 在結尾：目標$
str_subset(
  Rmdfiles, "[Rr][Mm][Dd]$"
)
```

```{r}
download.file("https://www.dropbox.com/s/o9kt3lxtx9pmjqj/homework2.Rmd?dl=1", destfile = "./hw2.Rmd", mode="wb")
xfun::read_utf8("./hw2.Rmd") -> hw2lines
View(hw2lines)

pick_starting3Hash <- str_detect(
  hw2lines,
  "^###"
)
sum(pick_starting3Hash)

pick_starting3Hash <- str_detect(
  hw2lines,
  "^### (?=[0-9])"
)
sum(pick_starting3Hash)
```

```{r}
library(purrr)
sukiyaMenu <- jsonlite::fromJSON("https://www.dropbox.com/s/iu9b1hnvbtss83q/sukiyaMenu.json?dl=1")

nonsetMenu3 <- sukiyaMenu[c("豪華雙饗丼", "牛丼類", "咖哩類" )]

items <- list()
items$dish_name = vector("list", length=3)

charVect <- vector("character", 5)
charVect
```

```{r}
# 餐點名稱
dish_name = nonsetMenu3[[1]]$name
items$dish_name[[1]] <- unlist(dish_name)

dish_name = nonsetMenu3[[2]]$name
items$dish_name[[2]] <- unlist(dish_name)

dish_name = nonsetMenu3[[3]]$name
items$dish_name[[3]] <- unlist(dish_name)

# programming block
# 餐點名稱
{
  dish_name <- nonsetMenu3[[1]]$name
  items$dish_name[[1]] <- unlist(dish_name)
}
{
  dish_name <- nonsetMenu3[[2]]$name
  items$dish_name[[2]] <- unlist(dish_name)
}
{
  dish_name <- nonsetMenu3[[3]]$name
  items$dish_name[[3]] <- unlist(dish_name)
}
```

```{r}
# result的值會是{...}裡最後一個expression的可視結果 
result <- {...} # 或
{...} -> result
```

```{r}
result1 <- {
  dish_name <- nonsetMenu3[[1]]$name # 1st expression
  items$dish_name[[1]] <- unlist(dish_name)  # 2nd expression
}
{
  dish_name <- nonsetMenu3[[1]]$name # 1st expression
  items$dish_name[[1]] <- unlist(dish_name)  # 2nd expression
} -> result2

result3 <- {
  dish_name <- nonsetMenu3[[1]]$name # 1st expression
  unlist(dish_name)  # 2nd expression
}

# cat(...)只會有螢幕資訊，但值不會留下來形成可視值。print(...)則會留下可視值
result4 <- {
  dish_name <- nonsetMenu3[[1]]$name # 1st expression
  cat(unlist(dish_name))  # 2nd expression
}
```

```{r}
mingsPrice <- # 找出小明價格
{
  sizeChoice <- nonsetMenu3[["豪華雙饗丼"]][["product_variations"]][[2]]
  pick_size <- sizeChoice$name == '飯大碗'
  sizeChoice$price[pick_size]
}

yingsPrice <- # 找出小英價格
{
  sizeChoice <- nonsetMenu3[["牛丼類"]][["product_variations"]][[4]]
  pick_size <- sizeChoice$name == '迷你碗'
  sizeChoice$price[pick_size]
}

total= mingsPrice + yingsPrice
```

### formula 
```{r}
library(purrr)
map(
  list(2,5,3,7),
  ~{
    3^.x
  }
)
map(
  c(2,5,3,7),
  ~{
    3^.x
  }
)

map(
  list(
    list("Mary", 5),
    list("John", 10)
  ),
  ~{
    paste0(.x[[1]], " is ",.x[[2]], " years old")
  }
)
```

### ok
```{r}
myData <- 
  list(
    list("Mary", 5),
    list("John", 10)
  )
# .x 代表myData的元素
map(
  myData,
  ~{
    paste0(.x[[1]], " is ",.x[[2]], " years old")
  }
)

# .x 代表myData元素值的位置
map(
  1:2,
  ~{
    paste0(myData[[.x]][[1]], " is ", myData[[.x]][[2]], " years old")
  }
)

# 1:length(object)
seq_along(object)

map(
  seq_along(myData),
  ~{
    paste0(myData[[.x]][[1]], " is ", myData[[.x]][[2]], " years old")
  }  
)
```

```{r}
{
  dish_name <- nonsetMenu3[[1]]$name # 1st expression
  unlist(dish_name)  # 2nd expression
}

{
  dish_name <- sukiyaMenu[[.x]]$name # 1st expression
  unlist(dish_name)  # 2nd expression
}

map(
  seq_along(sukiyaMenu),
  ~ {
    dish_name <- sukiyaMenu[[.x]]$name # 1st expression
    unlist(dish_name) # 2nd expression
  }
) -> result
result <- unlist(result[-1])
result
```
