---
title: "課堂練習模版"
author: "gary"
date: "2020-10-28"
output: html_document
params:
  id: "410678019"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
vector.example <- c("小明", "小英", "大雄")
vector.example.withnames <- c("p1"="小明","p2"="小英","p3"="大雄")
```

```{r}
vector.example
vector.example.withnames
names(vector.example.withnames)
```

```{r}
listExample <- list(student = "小明", 學期 = list(`108-1` = list(list(name = "個體經濟學", 
    teacher = "Alice", grade = 85)), `108-2` = list(list(name = "總體經濟學", 
    teacher = "Mark", grade = 78))))
# 有多少位置可選：
length(listExample)
listExample[[1]]
listExample[[2]]
```

```{r}
vector.example[c(1)]
vector.example[1]
vector.example[[1]]
vector.example.withnames[c("p1","p3")]
```

```{r}
vector.example
vector.example[c(T, T, F)]  # 要，要，不要
str(listExample[c(F, T)])  # 不要，要
str(listExample[c(T, T)])  # 要，要
```

```{r}
pick.by.number <- c(1,3)
pick.by.name <- c("p1","p3")
pick.by.logical <- c(T, F, T)
vector.example.withnames[pick.by.logical]
vector.example.withnames[pick.by.name]
vector.example.withnames[pick.by.number]
```

```{r}
listExample[1]
listExample[[1]]
```

```{r}
numVector <- c(2, 3, 6, -1, 4, 2, 6)
select1 <- numVector[c(1, 4)]
select1
select2 <- select1[[1]]
select2

# 相當於
numVector[c(1, 4)][[1]]
```

```{r}
select1 <- numVector[c(T, T, F, T, F, F, T)]
select1
select2 <- select1[c(1, 4)]
select2

# 相當於
numVector[c(T, T, F, T, F, F, T)][c(1, 4)]
```

```{r}
majors <- c("經濟學系", "經濟學系", "社會學系", "社工系", "經濟學系")
names <- c("小英", "小美", "大雄", "阿華", "阿尼")
gender <- c("F", "F", "M", "F", "M")
```

```{r}
today <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))
tomorrow <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))

weather <- list(today, tomorrow)

print(weather)
str(weather,1)
str(weather,2)
str(weather,3)
```


