---
title: "課堂練習模版"
author: "gary"
date: "2020-12-29"
output: html_document
params:
  id: "410678019"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
library(lubridate)
library(stringr)
library(purrr)

set.seed(10739)
customers <- data.frame(
  bills = sample(200:500, 10),
  vouchers = sample(c(T,F), size=10, replace=T,
                     prob=c(0.4,0.6)
                     )
)
head(customers)

bill <- customers$bills[[3]]
hasVoucher <- customers$vouchers[[3]]
totalBill <- 
{
  startingBill <- bill
  if(hasVoucher)
  {
    bill <- bill - 20
  }
  message("You initial bill is ", startingBill,".\n",
          "You final bill is ", bill)
  bill
}
print(totalBill)

get_totalBill <- function(bill, hasVoucher)
{
  startingBill <- bill
  if(hasVoucher)
  {
    bill <- bill - 20
  }
  message("You initial bill is ", startingBill,".\n",
          "You final bill is ", bill, "\n")
  bill
}

purrr::map2(
  customers$bills, customers$vouchers,
  ~get_totalBill(.x, .y)
)
```

### ok 
```{r}
f <- function(x){
  if(x<0)
  {
    stop("x has to be non-negative.")
  }
  sqrt(x)
}

f(-2)
f(2) 
```

### ok 
```{r}
comment_grade <- function(grade){
  if(grade < 60) return("Don't give up. There is still hope.")
  return("Good job. Keep going")
}

df_grades <- data.frame(
  grade=sample(50:95, 20, replace = T)
)
purrr::map_chr(
  df_grades$grade,
  comment_grade
) -> df_grades$comment
```

```{r}
grades <- c(55, 72, 40) # fail in first
# any one failed? 
if(grades < 60) message("\nYes, someone failed")

grades <- c(72, 55, 40) # fail in second
# any one failed? 
if(grades < 60) message("\nYes, someone failed")

# all() to flag if all failed.
# any() to flag if any failed.
grades <- c(72, 55, 82)
# any one failed? 
if(any(grades < 60)) message("\nYes, someone failed")

# Set length warning into an error
Sys.setenv("_R_CHECK_LENGTH_1_CONDITION_" = "true")
grades <- c(55, 72, 82)
# any one failed? 
if(grades < 60) message("\nYes, someone failed") # error now
```


```{r}
grade1 <- list(
  economics=55,
  calculus=77
)
grade2 <- c(
  economics=55,
  calculus=77
)

(is.list(grade1) &  grade1$economics > 60)
(is.list(grade2) &  grade2$economics > 60)

(is.list(grade1) && grade1$economics > 60)
(is.list(grade2) && grade2$economics > 60)
```

```{r}
myAge <- 75

if(myAge >=65 | stop("Error")){
  "Qualified"
} else {
  warning("Not qualified")
}

if(myAge >=65 ||  stop("Error")){
  "Qualified"
} else {
  warning("Not qualified")
}
```


```{r}
# 前提條件
x <- 4L
# 任務
fx <- {
  
  # ending scenario 1:
  {
    x/2
  }
  # ending scenario 2:
  {
    -(x+1)/2
  }
}

# 前提條件
x <- 4L
# 任務
fx <- {
  
  # ending scenario 1:
  if(x %% 2 ==0)
  {
    x/2
  } else
  # ending scenario 2:
  {
    -(x+1)/2
  }
}

fx

fx <- function(x)
{
  # ending scenario 1:
  if(x %% 2 ==0)
  {
    return(x/2)
  } else
  # ending scenario 2:
  {
    return(-(x+1)/2)
  }
}

fx(4L)
fx(7L)
```







